### ISSUE TITLE
question

### ISSUE THREAD

**Issue by syc-hjy** [ligerfotis/mvitac#1]
After downloading the dataset Calandra's Dataset, the data could not be prepared by the generate_dataset.py script, which could not satisfy the data preparation requirements for the training

**Comment by ligerfotis** [comment]
Can you please describe in detail the process you followed, the issue you are encountering, and the errors or warnings you get?

**Comment by syc-hjy** [comment]
When running create_dataset.ipynb as requested, it reports error keyerror i2 What is going on?





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ligerfotis/mvitac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月31日(星期三) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ligerfotis/mvitac] question (Issue #1)





 
Can you please describe in detail the process you followed, the issue you are encountering, and the errors or warnings you get?

**Comment by ligerfotis** [comment]
Please provide more detailed information. What is the full error log? In which cell do you encounter this error?

**Comment by ligerfotis** [comment]
I will close this thread as 'not planned'. If you have further questions or can provide a full error log, please let me know to reopen it.
