### ISSUE TITLE
why Comment “momentum_update_key_encoder” in function “forward” during the forward pass

### ISSUE THREAD

**Issue by wupeng1989** [ligerfotis/mvitac#2]
hi，i am very much appreciate your work.  I want to know why Comment “momentum_update_key_encoder” in function “forward” during the forward pass. The code is line 224 in  model.py

# # Perform momentum update during the forward pass
# momentum_update_key_encoder(self.vision_base_q, self.vision_base_k, self.vision_head_intra_q,
#                             self.vision_head_intra_k, self.m)
# momentum_update_key_encoder(self.tactile_base_q, self.tactile_base_k, self.tactile_head_intra_q,
#                             self.tactile_head_intra_k, self.m)

@ligerfotis

**Comment by ligerfotis** [comment]
It was commented out by accident. Las [commit](https://github.com/ligerfotis/mvitac/commit/a5b572dc3bdf5d8e210ec32d69bd0c82156a0cfa) has updated it.
